### ISSUE TITLE
authenticate with Google

### ISSUE THREAD

**Issue by torzsmokus** [lsiric/jira-log-time#2]
my organization uses Google Account (Apps) for authentication so I cannot provide a username/password. as far as I can see, it is not possible to use this extension in such a setup.

**Comment by lsiric** [comment]
Hi @torzsmokus , apologies, due to high volume of work, I am not able to extend the plugin with new auth options. Feel free to fork it and add any missing auth options you require.
Cheers!

**Comment by torzsmokus** [comment]
after the last update to cloud jira, we had to set up a password anyway, so my problem is kinda solved. :D

**Comment by torzsmokus** [comment]
anyone who is interested in implementing this: feel free to reopen.
