### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by tibu** [lsiric/jira-log-time#3]
Hi,

What is the licensing for the plugin? I'd like to add some functions to it (contribute to it or fork it).

Thanks

**Comment by lsiric** [comment]
Hi @tibu, it's free for all, feel free to fork 👍

**Comment by tibu** [comment]
Hi @lsiric , thanks this is great. 

However according to Github: 
'Code without an explicit license is protected by copyright and is by default All Rights Reserved. The person or people who wrote the code are protected as such. Any time you're using software you didn't write, licensing should be considered and abided.'

Could you please add some license to the main repo e.g. MIT?  http://choosealicense.com/licenses/

**Comment by lsiric** [comment]
Yup, already added MIT :)

**Comment by tibu** [comment]
Thanks, this was quick!
